<a href="https://colab.research.google.com/github/oscmoral/Programacion-para-analitica-descriptiva-y-predictiva/blob/main/Practica18_Datos_temporales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica 18: Datos Temporales

Nombre: Oscar Morales Martinez

Materia: Programación para analítica descriptiva y predictiva

Carrera: Maestría en Inteligencia Artificial y Analítica de Datos

## Instrucciones:

1. Descarga el archivo airdata.csv, proporcionado en esta tarea. También lo puedes encontrar en recursos.
2. Crea un notebook en colab y guarda el archivo csv  en tu drive.
3. Agrega secciones en el colab poniendo como título el nombre de cada ejercicio

## Ejercicio 01:Tipo de Datos Correcto

* Carga el conjunto de datos airdata.csv y verifica que cada columna tenga el tipo de datos correcto
* Si una columna de tipo temporal no está en el tipo de correcto realiza la conversión.
* Usa dtypes para mostrar que cada columna, principalmente la que contiene datos temporales, está en el tipo de datos correcto
* Imprime las primeras tres líneas

Paso 1: Importar librerias

In [ ]:
import pandas as pd
import numpy as np

Paso 2: Acceso a Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Paso 3: Carga el archivo a un dataframe.

In [ ]:
path = "/content/drive/MyDrive/ClassFiles/Airdata.csv"
df = pd.read_csv(path)

Paso 4: Verifica que cada columna tenga el tipo de datos correcto

In [ ]:
df.dtypes

DateTime           object
Temperature       float64
Humidity            int64
Wind_Speed        float64
Wind_Direction    float64
NO2_Location_A    float64
NO2_Location_B    float64
NO2_Location_C    float64
dtype: object

Paso 5: Si una columna de tipo temporal no está en el tipo de correcto realiza la conversión.

In [ ]:
if "DateTime" in df.columns:
    df["DateTime"] = pd.to_datetime(df["DateTime"], errors="coerce")

Paso 6: Usa dtypes para mostrar que cada columna, principalmente la que contiene datos temporales, está en el tipo de datos correcto

In [ ]:
df.dtypes

DateTime          datetime64[ns]
Temperature              float64
Humidity                   int64
Wind_Speed               float64
Wind_Direction           float64
NO2_Location_A           float64
NO2_Location_B           float64
NO2_Location_C           float64
dtype: object

Paso 7: Imprime las primeras tres líneas

In [ ]:
df.head(3)

,DateTime,Temperature,Humidity,Wind_Speed,Wind_Direction,NO2_Location_A,NO2_Location_B,NO2_Location_C
0,2020-01-01 00:00:00,2.180529,87,1.484318,75.96376,39.23,52.88,62.37
1,2020-01-01 01:00:00,1.490529,89,2.741678,113.19859,38.30,44.95,52.53
2,2020-01-01 02:00:00,1.690529,85,3.563818,135.00000,NaN,48.40,54.80

## Ejercicio 02: Extraer componentes de fecha y tiempo

* De la columna 'DateTime' extrae el año, mes, día y hora. Crea una nueva columna para cada componente que extraes
* Imprime las primeras tres líneas del dataframe que ahora deberá tener 4 nuevas columnas.

Paso 1: De la columna 'DateTime' extrae el año, mes, día y hora. Crea una nueva columna para cada componente que extraes

In [ ]:
df["year"] = df["DateTime"].dt.year
df["month"] = df["DateTime"].dt.month
df["day"] = df["DateTime"].dt.day
df["hour"] = df["DateTime"].dt.hour

Paso 2: Imprime las primeras tres líneas del dataframe que ahora deberá tener 4 nuevas columnas.

In [ ]:
df.head(3)

,DateTime,Temperature,Humidity,Wind_Speed,Wind_Direction,NO2_Location_A,NO2_Location_B,NO2_Location_C,year,month,day,hour
0,2020-01-01 00:00:00,2.180529,87,1.484318,75.96376,39.23,52.88,62.37,2020,1,1,0
1,2020-01-01 01:00:00,1.490529,89,2.741678,113.19859,38.30,44.95,52.53,2020,1,1,1
2,2020-01-01 02:00:00,1.690529,85,3.563818,135.00000,NaN,48.40,54.80,2020,1,1,2

## Ejercicio 03: Aritmética - Suma de Intervalos (timedelta)

* Suma 10 días, 7 horas y 15 minutos a cada elemento de la columna 'DateTime'.
* Guarda el resultado en una nueva columna y agrega al dataframe.
* Imprime la columna 'DateTime' y la columna que resulta de sumar 10 días, 7 horas y 15 minutos.

Paso 1: Suma 10 días, 7 horas y 15 minutos a cada elemento de la columna 'DateTime'.

In [ ]:
delta = pd.Timedelta(days=10, hours=7, minutes=15)

Paso 2: Guarda el resultado en una nueva columna y agrega al dataframe.

In [ ]:
df["New_DateTime"] = df["DateTime"] + delta

Paso 3: Imprime la columna 'DateTime' y la columna que resulta de sumar 10 días, 7 horas y 15 minutos.

In [ ]:
df[["DateTime", "New_DateTime"]].head(5)

             DateTime        New_DateTime
0 2020-01-01 00:00:00 2020-01-11 07:15:00
1 2020-01-01 01:00:00 2020-01-11 08:15:00
2 2020-01-01 02:00:00 2020-01-11 09:15:00
3 2020-01-01 03:00:00 2020-01-11 10:15:00
4 2020-01-01 04:00:00 2020-01-11 11:15:00

## Ejercicio 04: Timestamp

* Convierte la columna 'DateTime' la cual tiene un formato de fecha legible a a timestamp Unix. Guarda el resultado en una nueva columna
* Imprime las primeras tres filas de  la columna 'DateTime' y la columna que representa dicha fecha en timestamp Unix

Paso 1: Convierte la columna 'DateTime' la cual tiene un formato de fecha legible a a timestamp Unix. Guarda el resultado en una nueva columna

In [ ]:
df["DateTime_unix"] = df["DateTime"].astype("int64")

Paso 2: Imprime las primeras tres filas de la columna 'DateTime' y la columna que representa dicha fecha en timestamp Unix

In [ ]:
df[["DateTime", "DateTime_unix"]].head(5)

             DateTime        DateTime_unix
0 2020-01-01 00:00:00  1577836800000000000
1 2020-01-01 01:00:00  1577840400000000000
2 2020-01-01 02:00:00  1577844000000000000
3 2020-01-01 03:00:00  1577847600000000000
4 2020-01-01 04:00:00  1577851200000000000

## Ejercicio 05: Filtrado de Fechas

* Utiliza la columna 'DateTime' y Filtra aquellas fechas que son mayores a 2020-11-01
* Imprime el resultado

Paso 1: Utiliza la columna 'DateTime' y Filtra aquellas fechas que son mayores a 2020-11-01

In [ ]:
cutoff_date = pd.Timestamp("2020-11-01")
filtered_df = df[df["DateTime"] > cutoff_date]

Paso 2: Imprime el resultado

In [ ]:
filtered_df

,DateTime,Temperature,Humidity,Wind_Speed,Wind_Direction,NO2_Location_A,NO2_Location_B,NO2_Location_C,year,month,day,hour,New_DateTime,DateTime_unix
7321,2020-11-01 01:00:00,13.620529,58,6.638072,130.60129,17.50,23.88,44.07,2020,11,1,1,2020-11-11 08:15:00,1604192400000000000
7322,2020-11-01 02:00:00,13.980529,40,6.618519,157.61987,13.38,18.92,35.80,2020,11,1,2,2020-11-11 09:15:00,1604196000000000000
7323,2020-11-01 03:00:00,13.010529,43,8.209263,164.74487,11.95,13.95,30.15,2020,11,1,3,2020-11-11 10:15:00,1604199600000000000
7324,2020-11-01 04:00:00,12.190529,51,7.568566,154.65382,10.10,14.35,31.45,2020,11,1,4,2020-11-11 11:15:00,1604203200000000000
7325,2020-11-01 05:00:00,12.510529,59,7.594208,148.57043,10.30,14.42,32.55,2020,11,1,5,2020-11-11 12:15:00,1604206800000000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,2020-12-31 19:00:00,4.920528,72,4.553680,251.56506,53.44,32.65,66.82,2020,12,31,19,2021-01-11 02:15:00,1609441200000000000
8780,2020-12-31 20:00:00,4.990529,74,3.259939,186.34020,49.80,34.03,67.31,2020,12,31,20,2021-01-11 03:15:00,1609444800000000000
8781,2020-12-31 21:00:00,4.360529,84,10.587917,252.18112,43.32,25.55,59.33,2020,12,31,21,2021-01-11 04:15:00,1609448400000000000
8782,2020-12-31 22:00:00,3.820528,88,8.435069,219.80557,39.88,19.90,43.70,2020,12,31,22,2021-01-11 05:15:00,1609452000000000000
8783,2020-12-31 23:00:00,3.170529,89,6.792466,212.00539,39.04,30.33,46.87,2020,12,31,23,2021-01-11 06:15:00,1609455600000000000